const { formatName } = require('../format');

describe('format', () => {
  test('formatName', () => {
    expect(formatName('foo')).toEqual('Foo');
    expect(formatName('foo bar')).toEqual('Foo_Bar');
    expect(formatName('DJ foo')).toEqual('DJ_Foo');
    expect(formatName('the foo')).toEqual('The_Foo');
    expect(formatName('foo the')).toEqual('Foo_The');
    expect(formatName('Foo And Bar')).toEqual('Foo_and_Bar');
    expect(formatName('Foo Or Bar')).toEqual('Foo_or_Bar');
    expect(formatName('Foo Of Bar')).toEqual('Foo_of_Bar');
    expect(formatName('Foo But Bar')).toEqual('Foo_but_Bar');
    expect(formatName('Foo For Bar')).toEqual('Foo_for_Bar');
    expect(formatName('Foo Nor Bar')).toEqual('Foo_nor_Bar');
    expect(formatName('Foo The Bar')).toEqual('Foo_the_Bar');
    expect(formatName('Foo A Bar')).toEqual('Foo_a_Bar');
    expect(formatName('a foo')).toEqual('A_Foo');
    expect(formatName('foo a')).toEqual('Foo_A');
    expect(formatName('Foo An Bar')).toEqual('Foo_an_Bar');
    expect(formatName('Foo Down Bar')).toEqual('Foo_Down_Bar');
    expect(formatName('Foo Under Bar')).toEqual('Foo_Under_Bar');
    expect(formatName('Foo Over Bar')).toEqual('Foo_Over_Bar');
    expect(formatName('Foo To Bar')).toEqual('Foo_to_Bar');
    expect(formatName('Foo Through Bar')).toEqual('Foo_Through_Bar');
    expect(formatName('Foo During Bar')).toEqual('Foo_During_Bar');
    expect(formatName('Foo Without Bar')).toEqual('Foo_Without_Bar');
    expect(formatName('Foo On Bar')).toEqual('Foo_on_Bar');
    expect(formatName('Foo In Bar')).toEqual('Foo_in_Bar');
    expect(formatName('Foo By Bar')).toEqual('Foo_by_Bar');
    expect(formatName('Foo Off Bar')).toEqual('Foo_off_Bar');
    // expect(formatName('Foo X Bar')).toEqual('Foo_X_Bar');
    expect(formatName('Foo Pres Bar')).toEqual('Foo_pres_Bar');
    expect(formatName('Foo Vs Bar')).toEqual('Foo_vs_Bar');
    expect(formatName('Foo Feat Bar')).toEqual('Foo_feat_Bar');
    expect(formatName('Foo & Bar')).toEqual('Foo_and_Bar');
    // expect(formatName('&Foo')).toEqual('And Foo');
    // expect(formatName('Foo&')).toEqual('Foo And');
    expect(formatName('Foo + Bar')).toEqual('Foo_and_Bar');
    // expect(formatName('+Foo')).toEqual('And Foo');
    // expect(formatName('Foo+')).toEqual('Foo And');
    expect(formatName('Foo&Bar')).toEqual('Foo_and_Bar');
    expect(formatName('Foo+Bar')).toEqual('Foo_and_Bar');
    expect(formatName('Foo 12"')).toEqual('Foo_12in');
    expect(formatName('Foo.Bar')).toEqual('FooBar');
    expect(formatName('Foo %% Bar')).toEqual('Foo_Bar');
    expect(formatName('Foo  Bar')).toEqual('Foo_Bar');
    expect(formatName('Foo Bar ')).toEqual('Foo_Bar');
    expect(formatName(' Foo Bar')).toEqual('Foo_Bar');
    expect(formatName('  ')).toEqual('');
    expect(formatName('')).toEqual('');
  });
});
